//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AccesoDatosReportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportesEntities : DbContext
    {
        public ReportesEntities()
            : base("name=ReportesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ClientesMoroso> ClientesMorosos { get; set; }
        public virtual DbSet<Mora> Moras { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Prestamo> Prestamos { get; set; }
    }
}
