//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AccesoDatosReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoID { get; set; }
        public int PrestamoID { get; set; }
        public int Mes { get; set; }
        public decimal MontoAnterior { get; set; }
        public decimal InteresPagado { get; set; }
        public decimal MontoAbonado { get; set; }
        public decimal NuevoSaldo { get; set; }
        public System.DateTime FechaPago { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
