//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AccesoDatosReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amortizacion
    {
        public int AmortizacionID { get; set; }
        public int PrestamoID { get; set; }
        public int Mes { get; set; }
        public decimal Cuota { get; set; }
        public decimal Interes { get; set; }
        public decimal Capital { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Estado { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
