//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.AccesoDatosReportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesMoroso
    {
        public int ClienteMorosoID { get; set; }
        public int ClienteID { get; set; }
        public int CantidadMoras { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
